[workspace]
resolver = "2"
members = ["crates/classfile", "crates/jvm", "crates/decompiler", "crates/cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
jcdc-classfile = { path = "crates/classfile" }
jcdc-jvm = { path = "crates/jvm" }
jcdc-decompiler = { path = "crates/decompiler" }
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[profile.release]
debug = true
