[workspace]
resolver = "2"
members = ["crates/classfile", "crates/jvm", "crates/decompiler", "crates/cli"]

[workspace.package]
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/ejfkdev/jcdc"
homepage = "https://github.com/ejfkdev/jcdc"

[workspace.dependencies]
jcdc-classfile = { path = "crates/classfile", version = "0.1.1" }
jcdc-jvm = { path = "crates/jvm", version = "0.1.1" }
jcdc-decompiler = { path = "crates/decompiler", version = "0.1.1" }
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[profile.release]
debug = true
