[package]
name = "jcdc-jvm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Java class pool, type resolution and generic signature parsing for jcdc"

[dependencies]
jdc-core = { workspace = true }
jcdc-classfile = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
anyhow = { workspace = true }
zip = { version = "2", default-features = false, features = ["deflate"] }
